### ISSUE TITLE
Custom reference fasta file

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/artemis#17]
Hi .

so when I index a new reference fasta file, say , custom_Weird_FastaName.fa, and runKallisto, the software runs correctly.
However, mergekallisto throws an error when the fasta is not ERCC, Ensmbl, or Rep with strict naming convention.

if I change the reference to ERCC.fa ,  I can complete the run.

**Comment by ttriche** [comment]
Post full error output and I can fix this one.  Definitely a bug. 

--t

**Comment by arcolombo** [comment]
Here is the errror

mergeKallisto(appSession$samples, outputPath=appSession$outputPath,parallel, parallel=FALSE)

Found /data/trnaOutput/mut1 bootstraps, summarizing...
Error in if (type == "ErccDbLite") { : argument is of length zero

 system("cat /data/trnaOutput/mut3/run_info.json")
{
	"n_targets": 441,
	"n_bootstraps": 100,
	"n_processed": 3468700,
	"kallisto_version": "0.42.3",
	"index_version": 10,
	"start_time": "Wed Oct 21 19:32:48 2015",
	"call": "kallisto quant -i /Package_data/trnaFasta/ProcessedmethylatedReferencekallisto.0.42.3.fa.kidx -o /data/trnaOutput/mut3 -b 100 -t 1 --single -l 150 -s 0.001 /trna_raw_reads/mut3/10-mut-tRNAbis-3_S6_L001_R1_001.fastq.gz"
}

**Comment by ttriche** [comment]
Hopefully the most recent version of TxDbLite (or at least my fork of it) fixes this situation.  If you can provide me with the .h5 files and/or run with the most recent TxDbLite (commit ttriche/TxDbLite@d4f668f4b77af8891dc011e9416754d624f4a004 in my fork) I can verify this and close it.

**Comment by arcolombo** [comment]
I need to confirm this error with the new TxDbLite version, for closing this.

**Comment by arcolombo** [comment]
Here is the error 


 invalid class “KallistoExperiment” object: invalid object for slot "transcriptomes" in class "KallistoExperiment": got class "list", should be or extend class "character"
> 
here is the link

https://www.dropbox.com/sh/z2pg8vo10qlu7f5/AACSpVXB2vfbndJvog2JFMvla?dl=0


Essentially I created a custom reference and merged the results..... I pulled your branch, and hit the above error.

**Comment by arcolombo** [comment]
confirmed.
