### ISSUE TITLE
verify Travis build post-merges

### ISSUE THREAD

**Issue by ttriche** [RamsinghLab/artemis#28]
These were big ones.  Need to verify.

![image](https://cloud.githubusercontent.com/assets/4386/12373932/69b96868-bc40-11e5-83e0-075bd92fa1b8.png)

**Comment by ttriche** [comment]
Well, how about that. 

![lgtm_tattoo](https://cloud.githubusercontent.com/assets/4386/12373949/256e97f4-bc41-11e5-9344-41e6f66d18c8.jpg)

**Comment by arcolombo** [comment]
haha

**Comment by ttriche** [comment]
We appear to have survived. 
![lgtm_sb](https://cloud.githubusercontent.com/assets/4386/12373956/72306fd6-bc41-11e5-9b5f-0d96d9283194.jpg)

**Comment by arcolombo** [comment]
TxDbLite travis is still running, when that finishes I will switch up the travis to RamsinghLab ~ master and re-run everything.    HAHA

**Comment by arcolombo** [comment]
Yes, leave open for one more travis run pulling from RamsinghLab.   okay.  tyvm

**Comment by ttriche** [comment]
Woops, we await judgment after all.  My bad.

![embarrassed-chimpanzee](https://cloud.githubusercontent.com/assets/4386/12373962/c831a3fa-bc41-11e5-8a6c-27945d6776e4.jpg)

**Comment by arcolombo** [comment]
on my end I see that the travis builds completed and pulled from ramsinghLab.   now back to science.

**Comment by pimentel** [comment]
rofl...!
